### PR TITLE
Fix presigining

### LINKED ISSUE #283: Presigned links broken as of 0.32
**Describe the bug**
Presigned links are deemed invalid by AWS as of version 0.32.
They worked fine in version 0.31.

**To Reproduce**
Generate a presigned link in 0.32.
See the following error message back from AWS:
```xml
<Error>
<Code>InvalidToken</Code>
<Message>
The provided token is malformed or otherwise invalid.
</Message>
```

**Expected behavior**
*works*

**Environment**
 - Rust version: latest stable
 - lib version: `0.32.1`

**Additional context**

Looks like at least the `X-Amz-Security-Token` variable is not properly urlencoded in 0.32, while it does get properly urlencoded in previous versions.

### PR DESCRIPTION
**Pull request by Ten0**
FIX #283

Also remove a bunch of unnecessary intermediate string allocations

### CODE REVIEW

File: s3/src/signing.rs [hunk 1]
```diff
@@ -219,11 +224,16 @@ pub fn authorization_query_params_no_sig(
...
-        signed_headers = signed_headers_string
+        signed_headers = signed_headers,
     );
 
     if let Some(token) = token {
-        write!(query_params, "&X-Amz-Security-Token={}", token).expect("Could not write token");
+        write!(
+            query_params,
+            "&X-Amz-Security-Token={}",
+            utf8_percent_encode(token, FRAGMENT_SLASH)
```
Comment (Ten0) [inline s3/src/signing.rs:234]: this is the actual fix
